import google.generativeai as genai

from src.config.config import GOOGLE_REPLY_API_KEY


genai.configure(api_key=GOOGLE_REPLY_API_KEY)


async def generate_reply(post_content: str, comment_content: str) -> str:
    """
    Generates a relevant and useful response to a comment on a post, using the Google Reply API.

    Parameters:
        - post_content (str): The content of the post for which a response to the comment is being generated.
        - comment_content (str): The content of the comment for which a response is being generated.

    Returns:
        - str: A response to the comment that is relevant and useful, generated by the Google Reply API. If an error occurs during the generation process, a default response "Дякую за ваш коментар!" is returned.
    """
    prompt = f"""
    Пост: "{post_content}"
    Комментарий: "{comment_content}"
    Як автор посту, напиши відповідь на цей коментар, який буде релевантним та корисним.
    """.strip()

    try:
        model = genai.GenerativeModel("gemini-1.5-flash")
        response = await model.generate_content(prompt)
        return response.text
    except Exception as e:
        print(f"Error generating reply: {e}")
        return "Дякую за Ваш коментар!"
