"""Update models: bool status

Revision ID: c9dfde763d26
Revises: e824f42062c4
Create Date: 2024-10-19 21:25:45.284159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dfde763d26'
down_revision: Union[str, None] = 'e824f42062c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'censored',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('posts', 'censored',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'censored',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('comments', 'censored',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
