"""Update models: add censored to posts and comments

Revision ID: e824f42062c4
Revises: 4bc91c6ff13a
Create Date: 2024-10-19 21:21:59.964981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e824f42062c4'
down_revision: Union[str, None] = '4bc91c6ff13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('censored', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('censored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'censored')
    op.drop_column('comments', 'censored')
    # ### end Alembic commands ###
